/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MuonTraDAO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import model.AllDetails;
import static view.TraSachAdmin.strMaMT;
import static view.TraSachAdmin.strMaTL;
import static view.UserLoginFrame.idLoggin;

/**
 *
 * @author Admin
 */
public class ChiTietMTUser extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form ChiTietMTUser
     */
    public ChiTietMTUser() {
        initComponents();
        this.setTitle("Chi Tiết Mượn Trả");
        this.setLocationRelativeTo(null);
        btnCancel.addActionListener(this);
        btnShow.addActionListener(this);
        btnSearch.addActionListener(this);
        clickShow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTMT = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        boxSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCTMT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCTMT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Tài Liệu Đã Mượn");

        boxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ten Tai Lieu", "Ma Tai Lieu", "Ma Muon Tra" }));

        btnSearch.setText("Search");

        jLabel2.setText("Tìm Kiếm Thông Tin Tại Đây!");

        btnShow.setText("Show All");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(boxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShow)
                    .addComponent(btnCancel))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietMTUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietMTUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietMTUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietMTUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Set the jTattoo look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

        } catch (Exception e) {
            System.err.println("Look and feel not set.");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietMTUser().setVisible(true);
            }
        });
    }

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 120) {
                width = 120;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    public void clickShow() {
        int i = 1;
        ArrayList<AllDetails> listSer = new MuonTraDAO().getListCTForUser(idLoggin);
        DefaultTableModel modelTbl = new DefaultTableModel();

        modelTbl.setColumnIdentifiers(new Object[]{
            "STT", "MaMT", "MaTL", "TenTL", "AdminName", "NgayMuon", "HanTra", "NgayTra", "TienPhat", "GhiChu"
        });
        for (AllDetails dt : listSer) {
            modelTbl.addRow(new Object[]{
                i++, dt.getMaMT(), dt.getMaTL(), dt.getDocName(), dt.getAdminName(), dt.getNgayMuon(), dt.getHanTra(), dt.getNgayTra(), dt.getMoney(), dt.getNote()
            });
        }
        tblCTMT.setModel(modelTbl);//set model for table with new data
        resizeColumnWidth(tblCTMT);
    }

    public void clickSearch() {
        int i = 1;
        ArrayList<AllDetails> listS = new ArrayList<>();
        DefaultTableModel model = new DefaultTableModel();
        String strBox = boxSearch.getSelectedItem().toString();

        if (strBox.equals("Ten Tai Lieu")) {
            listS = new MuonTraDAO().getListCTForUserByName(txtSearch.getText(), idLoggin);
        } else if (strBox.equals("Ma Tai Lieu")) {
            listS = new MuonTraDAO().getListCTForUserByMaTL(txtSearch.getText(), idLoggin);
        } else if (strBox.equals("Ma Muon Tra")) {
            listS = new MuonTraDAO().getListCTForUserByMaMT(txtSearch.getText(), idLoggin);
        }
        model.setColumnIdentifiers(new Object[]{
            "STT", "MaMT", "MaTL", "TenTL", "AdminName", "NgayMuon", "HanTra", "NgayTra", "TienPhat", "GhiChu"
        });
        for (AllDetails dt : listS) {
            model.addRow(new Object[]{
                i++, dt.getMaMT(), dt.getMaTL(), dt.getDocName(), dt.getAdminName(), dt.getNgayMuon(), dt.getHanTra(), dt.getNgayTra(), dt.getMoney(), dt.getNote()
            });
        }
        tblCTMT.setModel(model);//set model for table with new data
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxSearch;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCTMT;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnCancel) {
            new UserView().setVisible(true);
            this.dispose();
        } else if (e.getSource() == btnShow) {
            clickShow();
        } else if (e.getSource() == btnSearch) {
            clickSearch();
        }
    }
}
