/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MuonTraDAO;
import static controller.MuonTraDAO.getConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.PhieuDKMuonTra;
import static view.AdminLoginFrame.idLogin;

/**
 *
 * @author Admin
 */
public class DKMuonTraView extends javax.swing.JFrame implements ActionListener {

    public static String userID, adminID;
    public static String maMT;
    public static String strNgayMuon;
    public static String adminName, userName;
    public static String strTienCoc;
    public static int tienCoc;

    /**
     * Creates new form PhieuDKMuonTra
     */
    public DKMuonTraView() {
        initComponents();
        this.setTitle("Đăng Ký Mượn Trả");
        this.setLocationRelativeTo(null);
        btnCancel.addActionListener(this);
        btnOK.addActionListener(this);
        btnReset.addActionListener(this);
        
        lbMoney.setText("");
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        txtNgayMuon.setText(sdf.format(date));//return String
        txtAdminID.setText(idLogin);
        txtAdmName.setText(getNameAdmin(txtAdminID.getText()));
    }

    public void switchPanel(JPanel pn) {
        pnDKMT.removeAll();
        pnDKMT.add(pn);
        pnDKMT.repaint();
        pnDKMT.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDKMT = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAdmName = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        txtAdminID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        txtMaMT = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTienCoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbMoney = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("AdminID");

        jLabel6.setText("AdminName");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phiếu Đăng Ký Mượn Trả");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("(*yyyy-MM-dd)");

        txtAdmName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAdmNameMouseClicked(evt);
            }
        });

        btnCancel.setText("Cancel");

        txtAdminID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAdminIDKeyPressed(evt);
            }
        });

        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });

        jLabel2.setText("Mã MT");

        jLabel3.setText("UserID");

        jLabel7.setText("Ngày Mượn");

        btnOK.setText("Ok");

        btnReset.setText("Reset");

        jLabel4.setText("UserName");

        txtUserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserIDKeyPressed(evt);
            }
        });

        txtNgayMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayMuonMouseClicked(evt);
            }
        });

        jLabel9.setText("Tiền cọc");

        txtTienCoc.setText("100000");
        txtTienCoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienCocKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("(* 50.000 đ/tài liệu )");

        lbMoney.setText("money here!");

        javax.swing.GroupLayout pnDKMTLayout = new javax.swing.GroupLayout(pnDKMT);
        pnDKMT.setLayout(pnDKMTLayout);
        pnDKMTLayout.setHorizontalGroup(
            pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnDKMTLayout.createSequentialGroup()
                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDKMTLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDKMTLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDKMTLayout.createSequentialGroup()
                                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaMT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnDKMTLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(25, 25, 25)
                                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnDKMTLayout.createSequentialGroup()
                                .addGap(376, 376, 376)
                                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnDKMTLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDKMTLayout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                        .addGap(16, 16, 16)
                                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAdmName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTienCoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnDKMTLayout.setVerticalGroup(
            pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDKMTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDKMTLayout.createSequentialGroup()
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(19, 19, 19)
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDKMTLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDKMTLayout.createSequentialGroup()
                                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))))
                    .addGroup(pnDKMTLayout.createSequentialGroup()
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdmName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMoney)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(pnDKMTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnDKMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDKMT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNgayMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayMuonMouseClicked
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        txtNgayMuon.setText(sdf.format(date));
    }//GEN-LAST:event_txtNgayMuonMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        // TODO add your handling code here:
        txtUserName.setText(getNameUser());
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtAdmNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAdmNameMouseClicked
        // TODO add your handling code here:
        txtAdmName.setText(getNameAdmin(txtAdminID.getText()));
    }//GEN-LAST:event_txtAdmNameMouseClicked

    private void txtUserIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUserName.setText(getNameUser());
        }
    }//GEN-LAST:event_txtUserIDKeyPressed

    private void txtAdminIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdminIDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtAdmName.setText(getNameAdmin(txtAdminID.getText()));
        }
    }//GEN-LAST:event_txtAdminIDKeyPressed

    private void txtTienCocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienCocKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTienCocKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DKMuonTraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DKMuonTraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DKMuonTraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DKMuonTraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Set the jTattoo look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

        } catch (Exception e) {
            System.err.println("Look and feel not set.");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DKMuonTraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lbMoney;
    public javax.swing.JPanel pnDKMT;
    private javax.swing.JTextField txtAdmName;
    private javax.swing.JTextField txtAdminID;
    private javax.swing.JTextField txtMaMT;
    private javax.swing.JTextField txtNgayMuon;
    public static javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void clickOK() {
        ArrayList<PhieuDKMuonTra> listDK = new ArrayList<>();
        PhieuDKMuonTra dkmt = new PhieuDKMuonTra();

        dkmt.setMaMT(txtMaMT.getText());
        dkmt.setUserID(Integer.parseInt(txtUserID.getText()));
        dkmt.setAdminID(Integer.parseInt(txtAdminID.getText()));
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dkmt.setNgayMuon(sdf.parse(txtNgayMuon.getText()));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        if (new MuonTraDAO().addDangKyMT(dkmt)) {
            JOptionPane.showMessageDialog(rootPane, "Successful!");
            userID = txtUserID.getText();
            adminID = txtAdminID.getText();
            maMT = txtMaMT.getText();
            strNgayMuon = txtNgayMuon.getText();
            adminName = txtAdmName.getText();
            userName = txtUserName.getText();
            strTienCoc = txtTienCoc.getText();
            tienCoc = Integer.valueOf(strTienCoc);
            listDK.add(dkmt);
            new ChiTietMuonTraADMIN().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR! Nhầm ID, hoặc MaMT đã Tồn Tại,...");
        }

    }

    public static String getNameAdmin(String adminID) {
        String adName = null;
        try {
            Connection con = getConnection();
            System.out.println("connect Success!");

            String query = "SELECT * FROM tbladmin WHERE AdminID = ?";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, adminID);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                adName = rs.getString(2);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return adName;
    }

    public String getNameUser() {
        String usrName = null;
        try {
            Connection con = getConnection();
            System.out.println("connect Success!");

            String query = "SELECT * FROM tbluser WHERE UserID = ?";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, txtUserID.getText());

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                usrName = rs.getString(2);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return usrName;
    }

    public void clickReset() {
        txtAdmName.setText("");
        txtAdminID.setText("");
        txtMaMT.setText("");
        txtNgayMuon.setText("");
        txtUserID.setText("");
        txtUserName.setText("");
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnCancel) {
            new AdminView().setVisible(true);
            this.dispose();
        } else if (e.getSource() == btnOK) {
            clickOK();
        } else if (e.getSource() == btnReset) {
            clickReset();
        }
    }
}
